### PR TITLE
Final Project

### PR DESCRIPTION
**Pull request by Reynaldito98**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hi! Thank you for submitting your code, it looks pretty good! It will need some refactoring, but most issues found should be easy for you to fix. Please find comments in the list below. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* Please check fonts on the page. Currently, all elements render Arial, but the design suggests Inter, Roboto Slab and Roboto for the page.
* https://prnt.sc/Bx0goKQIo9qo Navigation menu needs a little correcting to match the design. Please compare with figma how the active link should be accented: https://prnt.sc/byRFkx6-OuY6
* https://prnt.sc/TD27YZs4LWgK saved-news page. We don't need black margins at the top and bottom. The whole viewport should be white, the header should be pushed to the top.
* "Search" button needs white text
* Page content should be limited in width (about) and centered (cards and about): https://prnt.sc/Esu1ULivZO9t
* The "Home" page scrolls horizontally on all resolusions: https://prnt.sc/q2Xf_hw8NcKP. The saved-news page scrolls on all screens, when there are cards rendered on it.
* Buttons in popups have incorrect color

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Images should preserve their proportions https://prnt.sc/Ly_cM1C6I6js
* The "Home" page scrolls horizontally on all resolusions: https://prnt.sc/q2Xf_hw8NcKP
* https://prnt.sc/6w1qPgvt313W https://prnt.sc/jeTnjIT-ADh5 The project's not adapted to mobile screens

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Links in footer should be working links, opening in new tabs.

- [ ]  Classes are named according to BEM specifications.

* https://prnt.sc/PGTD1OreVIG9 Incorrectly used modifiers (Modifier can't be used without the entity it modifies). Also, digits and numbers in BEM class names are forbidden.
* https://prnt.sc/Np-txxsIoAWx Shoudn't be a block, this is an element of `main-page` block
* https://prnt.sc/nY079vDgoHG7 Similar elements needs the same class name (links in footer), they have the same styles. You can use modifiers to assign unique styles to these links depending on their state or content (text or icon). 

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* Links in `header` and `footer` should be in nav, ul or ul inside nav.
* `div` can't be direct children of `ul` (please check cards layout). We need `li` for cards. Or, remove `ul` and use `article` for cards

- [ ]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.

* `news-card__category` no need to use absolute at all, you can push this element down to the container bottom with flexbox. But if you need to use absolute, its parent needs relative.

- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Hover and other effects don't match the design

- [ ]  The design reuses components wherever possible.

* All popups can use the same component

- [ ]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [ ]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.

* Closing icons, "nothing found" icon, "unsuccessful search" icon

- [ ]  Raster and vector images have been optimized.

## Number of points: 33

**Comment by ImaliaNsk** [comment]
Great job with corrections, you have improved your code significantly! However, it will need a bit more refactoring.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* Font family of titles in "cards", `about` is incorrect, should be Roboto Slab
* The "Home" page scrolls horizontally on all resolusions: https://prnt.sc/q2Xf_hw8NcKP. The saved-news page scrolls on all screens, when there are cards rendered on it.
* "Search" button is styled incorrectly, should be blue, with white text. Currently, it's greyed out when to text is entered in the "Search" input.

* Buttons in popups have incorrect color

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The "Home" page scrolls horizontally on all resolusions: https://prnt.sc/q2Xf_hw8NcKP
* https://prnt.sc/DSSNa-EYQ1Mo The project's not adapted to mobile screens

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* https://prnt.sc/9ifs4Eht_1nw Incorrectly used modifiers (Modifier can't be used without the entity it modifies). Please fix all similar issues
* Incorrectly named modifiers: `header__font-color_white`. This should be a key-value modifier, not boolean

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [ ]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.

* `news-card__category` no need to use absolute at all, you can push this element down to the container bottom with flexbox. But if you need to use absolute, its parent needs relative.

- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [ ]  The design reuses components wherever possible.

* All popups can use the same component

- [ ]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Images have an `alt` attribute containing appropriate values.

* Closing icon in "registration successful" modal

- [ ]  Raster and vector images have been optimized.

## Number of points: 54

**Comment by ImaliaNsk** [comment]
The project's getting better with every round of corrections, good job! However, some issues still require your attention.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* Font family of titles in "cards" is incorrect, should be Roboto Slab
* It's necessary to remove list markers in cards: https://prnt.sc/PoFXrCWncupH
* The "Home" page scrolls horizontally on all desktop resolusions: https://prnt.sc/q2Xf_hw8NcKP. The saved-news page scrolls on all desktop screens, when there are cards rendered on it.
* Labels on cards are not seen, white text on white background
* caption in the card should be aligned to the bottom of the container. This can be done using flexbox and `auto` margins

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The "Home" and saved-news pages scroll horizontally on 791 - 892
* https://prnt.sc/7TnapHo4AAXI Home page looks differently than in figma
* Images should preserve their proportions
* saved-news page looks differently than in figma: https://prnt.sc/hrsFD09k4Y-Z
* Content should be centered on all screens: https://prnt.sc/-Bw6PtgKu_vs

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [ ]  The design reuses components wherever possible.

* All popups can use the same component

- [ ]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 64

**Comment by ImaliaNsk** [comment]
Almost there! Some more fixing is needed. Most attention is required by mobile layout and horizontal scroll issue. You've already done most of the work, there are only a few fixes left!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The "Home" page scrolls horizontally on all desktop resolusions: https://prnt.sc/q2Xf_hw8NcKP. The saved-news page scrolls on all desktop screens, when there are cards rendered on it. Be carefaul with using 100vw as `width`. remember that these units don't include the width of a vertical scrollbar. You can read more about it here: https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one/23367686 https://dev.to/tepythai/why-100vw-causes-horizontal-scrollbar-4nlm
* https://prnt.sc/7TnapHo4AAXI Home page navigation menu looks differently than in figma
* Images should preserve their proportions
* saved-news page navigation menu looks differently than in figma: https://prnt.sc/hrsFD09k4Y-Z

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 79

**Comment by ImaliaNsk** [comment]
Thanks for fixing responsive layout issues! The score remained the same, because issue with the scroll on desktop screens haven't been resolved, both pages still scroll: https://prnt.sc/b8fO327OjDBF So the project will need a bit more work.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The "Home" page scrolls horizontally on all desktop resolusions: https://prnt.sc/q2Xf_hw8NcKP. The saved-news page scrolls on all desktop screens, when there are cards rendered on it. Be carefaul with using 100vw as `width`. remember that these units don't include the width of a vertical scrollbar. You can read more about it here: https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one/23367686 https://dev.to/tepythai/why-100vw-causes-horizontal-scrollbar-4nlm

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 79

**Comment by ImaliaNsk** [comment]
Hi Reynaldo! Thanks for sending the code with corrections! However, the number of points didn't change, because the issues from the previous review are still there. Please find them below.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The "Home" page scrolls horizontally on all desktop resolusions: https://prnt.sc/q2Xf_hw8NcKP. The saved-news page scrolls on all desktop screens, when there are cards rendered on it. Be carefaul with using 100vw as `width`. remember that these units don't include the width of a vertical scrollbar. You can read more about it here: https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one/23367686 https://dev.to/tepythai/why-100vw-causes-horizontal-scrollbar-4nlm

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 79

**Comment by ImaliaNsk** [comment]
Great job, I'm glad to see you've fixed the scroll! The project is accepted, congratulations! I wish you success in your further projects!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 92

**Comment by Reynaldito98** [comment]
Thank you very much!!!!

**Pull request merged**
